/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/media/[id]': RouteRecordInfo<'/admin/media/[id]', '/admin/media/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/members': RouteRecordInfo<'/admin/members', '/admin/members', Record<never, never>, Record<never, never>>,
    '/admin/options': RouteRecordInfo<'/admin/options', '/admin/options', Record<never, never>, Record<never, never>>,
    '/admin/perchmounts/[id]': RouteRecordInfo<'/admin/perchmounts/[id]', '/admin/perchmounts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/projects/[id]': RouteRecordInfo<'/admin/projects/[id]', '/admin/projects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/sections/[id]': RouteRecordInfo<'/admin/sections/[id]', '/admin/sections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/data': RouteRecordInfo<'/app/data', '/app/data', Record<never, never>, Record<never, never>>,
    '/app/emptycheck': RouteRecordInfo<'/app/emptycheck', '/app/emptycheck', Record<never, never>, Record<never, never>>,
    '/app/highlights': RouteRecordInfo<'/app/highlights', '/app/highlights', Record<never, never>, Record<never, never>>,
    '/app/identifyprey': RouteRecordInfo<'/app/identifyprey', '/app/identifyprey', Record<never, never>, Record<never, never>>,
    '/app/me': RouteRecordInfo<'/app/me', '/app/me', Record<never, never>, Record<never, never>>,
    '/app/media/[id]': RouteRecordInfo<'/app/media/[id]', '/app/media/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app/media/hightlights': RouteRecordInfo<'/app/media/hightlights', '/app/media/hightlights', Record<never, never>, Record<never, never>>,
    '/app/members/': RouteRecordInfo<'/app/members/', '/app/members', Record<never, never>, Record<never, never>>,
    '/app/members/[id]': RouteRecordInfo<'/app/members/[id]', '/app/members/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app/options': RouteRecordInfo<'/app/options', '/app/options', Record<never, never>, Record<never, never>>,
    '/app/perchmounts/': RouteRecordInfo<'/app/perchmounts/', '/app/perchmounts', Record<never, never>, Record<never, never>>,
    '/app/perchmounts/[id]': RouteRecordInfo<'/app/perchmounts/[id]', '/app/perchmounts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app/perchmounts/pending': RouteRecordInfo<'/app/perchmounts/pending', '/app/perchmounts/pending', Record<never, never>, Record<never, never>>,
    '/app/projects/': RouteRecordInfo<'/app/projects/', '/app/projects', Record<never, never>, Record<never, never>>,
    '/app/projects/[id]': RouteRecordInfo<'/app/projects/[id]', '/app/projects/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/app/review': RouteRecordInfo<'/app/review', '/app/review', Record<never, never>, Record<never, never>>,
    '/app/sections/[id]': RouteRecordInfo<'/app/sections/[id]', '/app/sections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/auth/denied': RouteRecordInfo<'/auth/denied', '/auth/denied', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/me': RouteRecordInfo<'/me', '/me', Record<never, never>, Record<never, never>>,
  }
}
